name: mediaDelta
channels:
- anaconda-fusion
- defaults
dependencies:
- openssl=1.0.2l=0
- pip=9.0.1=py27_1
- python=2.7.13=0
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - decorator==4.0.11
  - imageio==2.1.2
  - moviepy==0.2.3.2
  - numpy==1.13.1
  - olefile==0.44
  - pillow==4.2.1
  - pyexifinfo==0.4.0
  - tqdm==4.11.2

